import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

  <nav className="flex gap-6 p-5 border-b bg-gray-100">
    <Link href="/">Home</Link>{" | "}
    <Link href="/about">About</Link>{" | "}
    <Link href="/projects">Projects</Link>{" | "}
    <Link href="/contact">Contact</Link>{" | "}
    <Link href="/health">Health</Link>
  </nav>

  <main className="p-6">
    {children}
  </main>

</body>
    </html>
  );
}
